name: 'hotel_data_platform'
version: '1.0.0'
config-version: 2

# Profiles directory
profile: 'hotel_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  hotel_data_platform:
    staging:
      +enabled: true
      +schema: staging
    mart:
      +enabled: true
      +schema: mart
    metrics:
      +enabled: true
      +schema: metrics

tests:
  hotel_data_platform:
    custom_tests:
      +enabled: true
